import numpy as np
arr=np.array([[1,2,3],[1,2,6]])
print("dimension=",arr.ndim)
print("shape of array",arr.shape)
print("the datatype of array",arr.dtype)
print("size of array",arr.size)
print("to transport",arr.T)
print("sum of all matrix",arr.sum())
print("sum of matrix in axis 1 ",arr.sum(axis=1))
print("max number in matrix",arr.max())
print("min number in matrix",arr.min())
print("max number in matrix in axis 1",arr.max(axis=1))
print("min number in matrix in axis 1",arr.min(axis=1))
print("",arr.cumsum())  
